resources:
  requests:
    cpu: "100m"
    memory: "100mi"
  limits:
    cpu: "1000m"
    memory: "200Mi"

antiAffinity: "soft"

replicas: "1"
minimumMasterNodes: "1"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi